services:
  nutrition-controller:
    build: ./EEP-NutritionController
    ports:
      - "8000:8000"
    depends_on:
      - food-analyzer
      - nutrition-predictor
      - microbiom-analyzer
      - glucose-monitor
    environment:
      - FOOD_ANALYZER_URL=http://food-analyzer:8001
      - NUTRITION_PREDICTOR_URL=http://nutrition-predictor:8002
      - MICROBIOM_ANALYZER_URL=http://microbiom-analyzer:8003
      - GLUCOSE_MONITOR_URL=http://glucose-monitor:8004
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-north-1
      - S3_BUCKET_NAME=nutritiondataset
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    networks:
      - nutrition-network

  food-analyzer:
    build: ./IEP-FoodAnalyzer
    ports:
      - "8001:8001"
    environment:
      - CLARIFAI_PAT=${CLARIFAI_PAT}
      - CLARIFAI_USER_ID=${CLARIFAI_USER_ID}
      - CLARIFAI_APP_ID=${CLARIFAI_APP_ID}
    networks:
      - nutrition-network

  nutrition-predictor:
    build: ./IEP-NutritionPredictor
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - nutrition-network

  microbiom-analyzer:
    build: ./IEP-MicrobiomAnalyzer
    ports:
      - "8003:8003"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-north-1
      - S3_BUCKET_NAME=nutritiondataset
    networks:
      - nutrition-network

  glucose-monitor:
    build: ./IEP-GlucoseMonitor
    ports:
      - "8004:8004"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=eu-north-1
      - S3_BUCKET_NAME=nutritiondataset
    networks:
      - nutrition-network

  frontend:
    build: ./UI-NutritionAnalyzer/frontend
    ports:
      - "3000:3000"
    depends_on:
      - nutrition-controller
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - nutrition-network
    
  #prometheus:
   # image: prom/prometheus
    #container_name: prometheus
    #ports:
    #  - "9090:9090"
    #volumes:
    #  - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    #networks:
     # - nutrition-network

  #grafana:
   # image: grafana/grafana
    #container_name: grafana
    #ports:
    #  - "3001:3000"
    #depends_on:
    #  - prometheus
    #networks:
    #  - nutrition-network


networks:
  nutrition-network:
    driver: bridge