global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nutrition-services'
    static_configs:
      - targets:
          - 'nutrition-controller:8000'
          - 'food-analyzer:8001'
          - 'nutrition-predictor:8002'
          - 'microbiom-analyzer:8003'
          - 'glucose-monitor:8004'
