name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Food Analyzer Service
      - name: Build and push Food Analyzer
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-FoodAnalyzer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/food-analyzer:latest
      
      # Nutrition Predictor Service
      - name: Build and push Nutrition Predictor
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-NutritionPredictor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nutrition-predictor:latest
      
      # Microbiome Analyzer Service
      - name: Build and push Microbiome Analyzer
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-MicrobiomAnalyzer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/microbiom-analyzer:latest
      
      # Glucose Monitor Service
      - name: Build and push Glucose Monitor
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-GlucoseMonitor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/glucose-monitor:latest
      
      # Nutrition Controller Service
      - name: Build and push Nutrition Controller
        uses: docker/build-push-action@v4
        with:
          context: ./EEP-NutritionController
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nutrition-controller:latest
      
      # UI Frontend
      - name: Build and push UI
        uses: docker/build-push-action@v4
        with:
          context: ./UI-NutritionAnalyzer/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ui-nutrition-analyzer:latest
