name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Upload Artifact Action
        uses: actions/upload-artifact@v3

      - name: Create .env file from Secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "CLARIFAI_PAT=${{ secrets.CLARIFAI_PAT }}" >> .env
          echo "CLARIFAI_USER_ID=${{ secrets.CLARIFAI_USER_ID }}" >> .env
          echo "CLARIFAI_APP_ID=${{ secrets.CLARIFAI_APP_ID }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> .env

      - name: Upload .env as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Now build and push all your images one by one
      - name: Build and push Food Analyzer
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-FoodAnalyzer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/food-analyzer:latest
      
      - name: Build and push Nutrition Predictor
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-NutritionPredictor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nutrition-predictor:latest
      
      - name: Build and push Microbiome Analyzer
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-MicrobiomAnalyzer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/microbiom-analyzer:latest
      
      - name: Build and push Glucose Monitor
        uses: docker/build-push-action@v4
        with:
          context: ./IEP-GlucoseMonitor
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/glucose-monitor:latest
      
      - name: Build and push Nutrition Controller
        uses: docker/build-push-action@v4
        with:
          context: ./EEP-NutritionController
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nutrition-controller:latest
      
      - name: Build and push UI Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./UI-NutritionAnalyzer/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ui-nutrition-analyzer:latest
